# copy this to godot repo root and run to build
scons `
platform="web" `
production="yes" `
verbose="no" `
target="template_release" `
optimize="size_extra" `
threads="no" `
lto="full" `
build_profile="../../deparr/boids-cs/web_small.gdbuild" `
disable_3d="yes" `
use_llvm="yes" `
module_mono_enabled="no" `
module_text_server_adv_enabled="no" `
module_text_server_fb_enabled="yes" `
disable_physics_2d="yes" `
disable_physics_3d="yes" `
disable_navigation_2d="yes" `
disable_navigation_3d="yes" `
disable_xr="yes" `
module_godot_physics_2d_enabled="no" `
module_godot_physics_3d_enabled="no"

# use_closure_compiler="no" `
# module_jpg_enabled="no" `
# module_astcenc_enabled="yes" `
# module_basis_universal_enabled="yes" `
# module_bcdec_enabled="yes" `
# module_bmp_enabled="no" `
# module_camera_enabled="no" `
# module_csg_enabled="no" `
# module_dds_enabled="yes" `
# module_enet_enabled="no" `
# module_etcpak_enabled="yes" `
# module_fbx_enabled="no" `
# module_gltf_enabled="no" `
# module_gridmap_enabled="no" `
# module_hdr_enabled="no" `
# module_interactive_music_enabled="no" `
# module_jolt_physics_enabled="no" `
# module_jsonrpc_enabled="no" `
# module_ktx_enabled="yes" `
# module_lightmapper_rd_enabled="no" `
# module_mbedtls_enabled="no" `
# module_meshoptimizer_enabled="no" `
# module_mobile_vr_enabled="no" `
# module_mp3_enabled="no" `
# module_msdfgen_enabled="no" `
# module_multiplayer_enabled="no" `
# module_navigation_2d_enabled="no" `
# module_navigation_3d_enabled="no" `
# module_noise_enabled="no" `
# module_objectdb_profiler_enabled="no" `
# module_ogg_enabled="no" `
# module_openxr_enabled="no" `
# module_png_enabled="yes" `
# module_raycast_enabled="no" `
# module_regex_enabled="no" `
# module_svg_enabled="no" `
# module_tga_enabled="no" `
# module_theora_enabled="no" `
# module_tinyexr_enabled="yes" `
# module_upnp_enabled="no" `
# module_vhacd_enabled="no" `
# module_visual_shader_enabled="no" `
# module_vorbis_enabled="no" `
# module_webp_enabled="no" `
# module_webrtc_enabled="yes" `
# module_websocket_enabled="no" `
# module_webxr_enabled="no" `
# module_zip_enabled="no"
